title: Swift & AI
description: A blog about iOS development, Swift, and practical AI.
baseurl: ""
url: "https://swiftandai.com"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Eugenio Barqu√≠n"
  email: ""
