title: Swift & AI
email: ""
description: "A blog about iOS development, Swift, and practical AI."
baseurl: ""
url: "https://swiftandai.com"

author: "Eugenio Barqu√≠n"

theme: minima

minima:
  social_links: []

plugins:
  - jekyll-feed
  - jekyll-seo-tag
